# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Download labels

on:
  #push:
  #  branches: [ main ]
  schedule:
    - cron: "0 3 1 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: exec fetecher
      run: |
        python fetcher.py -a label
    - name: Commit files
      run: |
        git config --global user.email "allenstorm2005@gmail.com"
        git config --global user.name "Raingel(Github Action)"
        git add .
        git commit -m "last update: `date '+%Y-%m-%d %H:%M:%S'`"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
